version: '3.9'

services:
  postgres:
    container_name: cocoindex_postgres
    image: pgvector/pgvector:pg17
    ports:
        - "5543:5432"  # Change host port from 5432 to 5543
    environment:
      POSTGRES_DB: cocoindex
      POSTGRES_USER: cocoindex
      POSTGRES_PASSWORD: cocoindex
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cocoindex"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:

